### ISSUE TITLE
Improvement: allow `sync` to be done from filesystem instead of Git repo

### ISSUE THREAD

**Issue by SamTheisens** [TykTechnologies/tyk-git#6]
For our CI/CD setup, the possibility to `dump` and `sync` to and from the local filesystem would simplify matters quite a bit.
In our CI environment (Jenkins), we tend to check out a feature branch and build and deploy to our test environments from there. Then, once the code has been merged to master, we deploy to acceptance and production from there. In all scenarios the local filesystem contains the Tyk API definitions that we want to deploy.

A cli argument for the sync command with the path to the source files on disk instead of a git repository would simplify this tool and make it VCS agnostic.

**Comment by asoorm** [comment]
A git repo can be on your local filesystem and doesn't necessarily need to be remotely hosted github/bitbucket/gitlab.

**Comment by asoorm** [comment]
initialise local git repo

```
mkdir ~/foo && cd ~/foo
git init
```

General Workflow:
```
tyk-git dump -d http://dev.dashboard:3000 -s $DEV_DASH_KEY
git add .
git commit -m "my first commit"
tyk-git sync -d http://prod.dashboard:3000 -o $ORG_ID -s $PROD_DASH_KEY ~/foo/.git -b refs/heads/master
```
